/**
 * Client-safe form field definitions for the admin editor. Keep in sync with
 * the zod schemas in `src/lib/validation/admin.ts`.
 */
export type FieldType = "text" | "textarea" | "number" | "boolean" | "select" | "date" | "list" | "url" | "college" | "branch" | "department" | "source" | "recruiter";

export type FieldDef = {
  name: string;
  label: string;
  type: FieldType;
  required?: boolean;
  options?: { value: string; label: string }[];
  hint?: string;
};

const opts = (values: readonly string[]) => values.map((v) => ({ value: v, label: v.replace(/_/g, " ").toLowerCase().replace(/^\w/, (c) => c.toUpperCase()) }));

const srcFields: FieldDef[] = [
  { name: "sourceId", label: "Source", type: "source", hint: "Where this record was verified from." },
  { name: "isDemo", label: "Demo / sample data", type: "boolean" },
];

export const ADMIN_FIELDS: Record<string, FieldDef[]> = {
  sources: [
    { name: "name", label: "Name", type: "text", required: true },
    { name: "publisher", label: "Publisher", type: "select", options: opts(["KEA", "College", "VTU", "NBA", "NAAC", "AICTE", "Government", "Institutional report", "Demo", "Other"]) },
    { name: "url", label: "URL", type: "url" },
    { name: "publicationYear", label: "Publication year", type: "number" },
    { name: "lastVerifiedAt", label: "Last verified", type: "date" },
    { name: "notes", label: "Notes", type: "textarea" },
    { name: "isDemo", label: "Demo / sample data", type: "boolean" },
  ],
  colleges: [
    { name: "code", label: "KEA college code", type: "text", required: true },
    { name: "name", label: "Name", type: "text", required: true },
    { name: "shortName", label: "Short name", type: "text" },
    { name: "slug", label: "URL slug", type: "text", hint: "Leave blank to derive from the name." },
    { name: "type", label: "Type", type: "select", options: opts(["GOVERNMENT", "AIDED", "PRIVATE", "UNIVERSITY", "DEEMED"]), required: true },
    { name: "establishedYear", label: "Established year", type: "number" },
    { name: "district", label: "District", type: "text", required: true },
    { name: "city", label: "City", type: "text", required: true },
    { name: "address", label: "Address", type: "textarea" },
    { name: "pincode", label: "Pincode", type: "text" },
    { name: "affiliation", label: "Affiliation", type: "text" },
    { name: "university", label: "University", type: "text" },
    { name: "accreditation", label: "Accreditation (one per line)", type: "list" },
    { name: "autonomous", label: "Autonomous", type: "boolean" },
    { name: "hostelAvailable", label: "Hostel available", type: "boolean" },
    { name: "website", label: "Website", type: "url" },
    { name: "email", label: "Email", type: "text" },
    { name: "phone", label: "Phone", type: "text" },
    { name: "principal", label: "Principal / Director", type: "text" },
    { name: "campusAcres", label: "Campus size (acres)", type: "number" },
    { name: "imageUrl", label: "Cover image URL", type: "url" },
    { name: "description", label: "Description", type: "textarea" },
    { name: "history", label: "History", type: "textarea" },
    { name: "vision", label: "Vision", type: "textarea" },
    { name: "mission", label: "Mission", type: "textarea" },
    { name: "lastVerifiedAt", label: "Last verified", type: "date" },
    ...srcFields,
  ],
  branches: [
    { name: "code", label: "KEA branch code", type: "text", required: true },
    { name: "slug", label: "URL slug", type: "text", required: true },
    { name: "name", label: "Name", type: "text", required: true },
    { name: "shortName", label: "Short name", type: "text", required: true },
    { name: "category", label: "Category", type: "select", options: opts(["COMPUTING", "ELECTRONICS", "ELECTRICAL", "MECHANICAL", "CIVIL", "CHEMICAL", "AEROSPACE", "BIOTECH", "OTHER"]) },
    { name: "durationYears", label: "Duration (years)", type: "number" },
    { name: "about", label: "About", type: "textarea" },
    { name: "subjects", label: "Subjects (one per line)", type: "list" },
    { name: "careers", label: "Careers (one per line)", type: "list" },
    { name: "higherStudies", label: "Higher studies (one per line)", type: "list" },
    { name: "skills", label: "Skills (one per line)", type: "list" },
  ],
  departments: [
    { name: "collegeId", label: "College", type: "college", required: true },
    { name: "name", label: "Name", type: "text", required: true },
    { name: "slug", label: "Slug", type: "text", required: true },
    { name: "hod", label: "Head of department", type: "text" },
    { name: "about", label: "About", type: "textarea" },
    { name: "researchAreas", label: "Research areas (one per line)", type: "list" },
    { name: "studentActivities", label: "Student activities", type: "textarea" },
    ...srcFields,
  ],
  "college-branches": [
    { name: "collegeId", label: "College", type: "college", required: true },
    { name: "branchId", label: "Branch", type: "branch", required: true },
    { name: "departmentId", label: "Department", type: "department" },
    { name: "intake", label: "Intake", type: "number" },
    { name: "startedYear", label: "Started year", type: "number" },
    { name: "nbaAccredited", label: "NBA accredited", type: "boolean" },
    { name: "isDemo", label: "Demo / sample data", type: "boolean" },
  ],
  cutoffs: [
    { name: "collegeId", label: "College", type: "college", required: true },
    { name: "branchId", label: "Branch", type: "branch", required: true },
    { name: "year", label: "Year", type: "number", required: true },
    { name: "round", label: "Round", type: "number", required: true },
    { name: "category", label: "Category", type: "select", options: opts(["GM", "GMK", "GMR", "GMP", "1G", "1K", "1R", "2AG", "2AK", "2AR", "2BG", "2BK", "2BR", "3AG", "3AK", "3AR", "3BG", "3BK", "3BR", "SCG", "SCK", "SCR", "STG", "STK", "STR", "NRI", "OPN", "OTH"]), required: true },
    { name: "gender", label: "Gender", type: "select", options: opts(["ALL", "MALE", "FEMALE"]) },
    { name: "seatType", label: "Seat type", type: "select", options: opts(["GENERAL", "HYDERABAD_KARNATAKA", "RURAL", "KANNADA_MEDIUM", "SNQ", "OTHER"]) },
    { name: "openingRank", label: "Opening rank", type: "number" },
    { name: "closingRank", label: "Closing rank", type: "number", required: true },
    ...srcFields,
  ],
  fees: [
    { name: "collegeId", label: "College", type: "college", required: true },
    { name: "branchId", label: "Branch (blank = all)", type: "branch" },
    { name: "year", label: "Year", type: "number", required: true },
    { name: "quota", label: "Quota", type: "select", options: opts(["KCET", "COMEDK", "MANAGEMENT", "NRI", "OTHER"]), required: true },
    { name: "tuitionFee", label: "Tuition fee (₹)", type: "number", required: true },
    { name: "universityFee", label: "University / VTU fee (₹)", type: "number" },
    { name: "examFee", label: "Exam fee (₹)", type: "number" },
    { name: "otherFee", label: "Other mandatory (₹)", type: "number" },
    { name: "hostelFee", label: "Hostel fee (₹)", type: "number" },
    { name: "messFee", label: "Mess fee (₹)", type: "number" },
    { name: "notes", label: "Notes", type: "textarea" },
    ...srcFields,
  ],
  faculty: [
    { name: "collegeId", label: "College", type: "college", required: true },
    { name: "departmentId", label: "Department", type: "department" },
    { name: "name", label: "Name", type: "text", required: true },
    { name: "designation", label: "Designation", type: "text" },
    { name: "qualification", label: "Qualification", type: "text" },
    { name: "specialization", label: "Specialization", type: "text" },
    { name: "researchInterests", label: "Research interests (one per line)", type: "list" },
    { name: "experienceYears", label: "Experience (years)", type: "number" },
    { name: "profileUrl", label: "Official profile URL", type: "url" },
    { name: "publications", label: "Publications", type: "textarea" },
    ...srcFields,
  ],
  facilities: [
    { name: "collegeId", label: "College", type: "college", required: true },
    { name: "name", label: "Name", type: "text", required: true },
    { name: "category", label: "Category", type: "select", options: opts(["ACADEMIC", "LIBRARY", "SPORTS", "MEDICAL", "TRANSPORT", "DINING", "TECHNOLOGY", "SECURITY", "RESIDENTIAL", "RECREATION", "OTHER"]) },
    { name: "description", label: "Description", type: "textarea" },
    ...srcFields,
  ],
  laboratories: [
    { name: "collegeId", label: "College", type: "college", required: true },
    { name: "departmentId", label: "Department", type: "department" },
    { name: "name", label: "Name", type: "text", required: true },
    { name: "purpose", label: "Purpose", type: "textarea" },
    { name: "equipment", label: "Equipment (one per line)", type: "list" },
    { name: "imageUrl", label: "Image URL", type: "url" },
    ...srcFields,
  ],
  hostels: [
    { name: "collegeId", label: "College", type: "college", required: true },
    { name: "type", label: "Type", type: "select", options: opts(["BOYS", "GIRLS", "COED"]), required: true },
    { name: "name", label: "Name", type: "text" },
    { name: "capacity", label: "Capacity", type: "number" },
    { name: "feePerYear", label: "Hostel fee / year (₹)", type: "number" },
    { name: "messFeePerYear", label: "Mess fee / year (₹)", type: "number" },
    { name: "wifi", label: "Wi-Fi", type: "boolean" },
    { name: "studyArea", label: "Study area", type: "boolean" },
    { name: "security", label: "Security", type: "text" },
    { name: "distanceFromCampus", label: "Distance from academic block", type: "text" },
    { name: "transport", label: "Transport", type: "text" },
    { name: "rules", label: "Rules", type: "textarea" },
    ...srcFields,
  ],
  placements: [
    { name: "collegeId", label: "College", type: "college", required: true },
    { name: "departmentId", label: "Department (blank = college-wide)", type: "department" },
    { name: "year", label: "Year", type: "number", required: true },
    { name: "placementPercent", label: "Placement %", type: "number" },
    { name: "studentsPlaced", label: "Students placed", type: "number" },
    { name: "studentsEligible", label: "Students eligible", type: "number" },
    { name: "highestPackage", label: "Highest package (LPA)", type: "number" },
    { name: "averagePackage", label: "Average package (LPA)", type: "number" },
    { name: "medianPackage", label: "Median package (LPA)", type: "number" },
    { name: "lowestPackage", label: "Lowest package (LPA)", type: "number" },
    { name: "recruitersCount", label: "Number of recruiters", type: "number" },
    { name: "internshipInfo", label: "Internship information", type: "textarea" },
    ...srcFields,
  ],
  recruiters: [
    { name: "name", label: "Company", type: "text", required: true },
    { name: "sector", label: "Sector", type: "select", options: opts(["IT", "CORE", "ELECTRONICS", "CONSULTING", "FINANCE", "AUTOMOTIVE", "MANUFACTURING", "STARTUP", "OTHER"]) },
    { name: "website", label: "Website", type: "url" },
  ],
  "college-recruiters": [
    { name: "collegeId", label: "College", type: "college", required: true },
    { name: "recruiterId", label: "Recruiter", type: "recruiter", required: true },
    { name: "year", label: "Year", type: "number" },
    { name: "isDemo", label: "Demo / sample data", type: "boolean" },
  ],
  events: [
    { name: "collegeId", label: "College", type: "college", required: true },
    { name: "departmentId", label: "Department", type: "department" },
    { name: "name", label: "Name", type: "text", required: true },
    { name: "type", label: "Type", type: "select", options: opts(["TECHNICAL_FEST", "CULTURAL_FEST", "SPORTS", "WORKSHOP", "SEMINAR", "CONFERENCE", "HACKATHON", "CODING_COMPETITION", "STUDENT_ACTIVITY", "OTHER"]) },
    { name: "year", label: "Year", type: "number", required: true },
    { name: "date", label: "Date", type: "date" },
    { name: "participants", label: "Participants", type: "number" },
    { name: "description", label: "Description", type: "textarea" },
    { name: "results", label: "Results", type: "textarea" },
    { name: "imageUrl", label: "Image URL", type: "url" },
    ...srcFields,
  ],
  hackathons: [
    { name: "collegeId", label: "College", type: "college", required: true },
    { name: "name", label: "Name", type: "text", required: true },
    { name: "year", label: "Year", type: "number", required: true },
    { name: "organizer", label: "Organizer", type: "text" },
    { name: "participants", label: "Participants", type: "number" },
    { name: "winners", label: "Winners", type: "textarea" },
    { name: "projects", label: "Projects", type: "textarea" },
    { name: "sponsors", label: "Sponsors (one per line)", type: "list" },
    { name: "link", label: "Link", type: "url" },
    { name: "imageUrl", label: "Image URL", type: "url" },
    ...srcFields,
  ],
  clubs: [
    { name: "collegeId", label: "College", type: "college", required: true },
    { name: "departmentId", label: "Department", type: "department" },
    { name: "name", label: "Name", type: "text", required: true },
    { name: "category", label: "Category", type: "select", options: opts(["TECHNICAL", "CULTURAL", "SPORTS", "SOCIAL", "ENTREPRENEURSHIP", "PROFESSIONAL", "OTHER"]) },
    { name: "description", label: "Description", type: "textarea" },
    { name: "activities", label: "Activities (one per line)", type: "list" },
    { name: "achievements", label: "Achievements", type: "textarea" },
    { name: "contactLink", label: "Contact / social link", type: "url" },
    ...srcFields,
  ],
  achievements: [
    { name: "collegeId", label: "College", type: "college", required: true },
    { name: "year", label: "Year", type: "number", required: true },
    { name: "title", label: "Title", type: "text", required: true },
    { name: "description", label: "Description", type: "textarea" },
    ...srcFields,
  ],
  milestones: [
    { name: "collegeId", label: "College", type: "college", required: true },
    { name: "year", label: "Year", type: "number", required: true },
    { name: "title", label: "Title", type: "text", required: true },
    { name: "description", label: "Description", type: "textarea" },
    ...srcFields,
  ],
  images: [
    { name: "collegeId", label: "College", type: "college", required: true },
    { name: "url", label: "Image URL", type: "url", required: true },
    { name: "caption", label: "Caption", type: "text" },
    { name: "credit", label: "Credit / licence", type: "text" },
    { name: "isDemo", label: "Demo / sample data", type: "boolean" },
  ],
};

export const ADMIN_NAV: { key: string; label: string; group: string }[] = [
  { key: "colleges", label: "Colleges", group: "Institutions" },
  { key: "departments", label: "Departments", group: "Institutions" },
  { key: "branches", label: "Branches", group: "Institutions" },
  { key: "college-branches", label: "College ↔ Branch", group: "Institutions" },
  { key: "cutoffs", label: "Cutoffs", group: "Admissions" },
  { key: "fees", label: "Fees", group: "Admissions" },
  { key: "placements", label: "Placements", group: "Careers" },
  { key: "recruiters", label: "Recruiters", group: "Careers" },
  { key: "college-recruiters", label: "College ↔ Recruiter", group: "Careers" },
  { key: "faculty", label: "Faculty", group: "Campus" },
  { key: "facilities", label: "Facilities", group: "Campus" },
  { key: "laboratories", label: "Laboratories", group: "Campus" },
  { key: "hostels", label: "Hostels", group: "Campus" },
  { key: "images", label: "Images", group: "Campus" },
  { key: "events", label: "Events", group: "Student life" },
  { key: "hackathons", label: "Hackathons", group: "Student life" },
  { key: "clubs", label: "Clubs", group: "Student life" },
  { key: "achievements", label: "Achievements", group: "History" },
  { key: "milestones", label: "Milestones", group: "History" },
  { key: "sources", label: "Sources", group: "Data quality" },
];
